apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: centos-stream9-azure-vm1
spec:
  template:
    spec:
      domain:
        devices:
          interfaces:
            - macAddress: '02:bd:b0:00:00:01'  # Une adresse MAC unique
